pipeline {

    agent {label "dev1c" }

    options { timestamps() }
    
    stages {
        stage('Connection test') {
            steps { 
                timestamps {
                    script {
                        print  "I am alive!"
                    }
                }
            }
        }
    }
}